version: "3.9"
services:
    webapp:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./html:/usr/share/nginx/html
        networks:
            - frontend
networks:
    frontend:
