version: "3.9"
services:
    webapp:
        image: arfanxn/nginx:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NGINX_VERSION: latest
        environment:
            - NGINX_PORT=80
            - NGINX_DOMAIN_NAME=dev01.dimas-maryanto.com
            - NGINX_ROOT_DOCUMENT=/var/www/html
