version: "3.9"
services:
    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
        volumes:
            - mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        ports:
            - 33306:80
        environment:
            - MYSQL_ROOT_PASSWORD
        profiles:
            - debug
        depends_on:
            - db
volumes:
    mysql_data:
