version: "3.9"
services:
    mysql:
        image: mysql:latest
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql_data:/var/lib/mysql
volumes:
    mysql_data:
