version: "3.9"
services:
    mysql:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
    laravel:
        image: arfanxn/laravel-8:latest
        environment:
            - APP_URL=""
        restart: always
volumes:
    db_data:
