version: "3.8"
services:
    webapp:
        image: nginx:latest
        ports:
            - "8080:80"
    db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - "31432:5432"
