version: "3.8"
services:
    nginx1:
        privileged: true
        labels:
            - env=development
        image: nginx
        ports:
            - 8081:80
        volumes:
            - ./assets:/usr/share/nginx/html
    nginx2:
        privileged: true
        labels:
            - env=stagging
        image: nginx
        ports:
            - 8082:80
        volumes:
            - ./assets:/usr/share/nginx/html
