version: "3.8"
services:
    proxy:
        image: nginx:latest
        ports:
            - 8080:80
        environment:
            - APPLICATION_PORT=80
            - NGINX_ROOT_DOCUMENT=/usr/share/nginx/html
            - BACKEND_HOST=backend
            - BACKEND_PORT=80
            - BACKEND_CONTEXT_PATH=/
        volumes:
            - ./nginx/default.template.conf:/etc/nginx/templates/default.conf.template
    backend:
        image: nginx:latest
        volumes:
            - ./html/index.html:/usr/share/nginx/html/index.html
        expose:
            - 80
