version: "3.9"
services:
    wordpress:
        image: wordpress:latest
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: wordpress_user
            WORDPRESS_DB_NAME: wordpress_db
        networks:
            - backend
            - frontend
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: wordpress_user
            MYSQL_ROOT_PASSWORD: secretPassword
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend
    proxy:
        image: nginx:latest
        ports:
            - 8080:80
        environment:
            - WORDPRESS_HOST=wordpress
            - WORDPRESS_PORT=80
            - WORDPRESS_CONTEXT_PATH=/
        networks:
            - frontend
        volumes:
            - type: bind
              source: ./nginx/wordpress-proxy.nginx.template.conf
              target: /etc/nginx/templates/default.conf.template
volumes:
    mysql_data:
networks:
    frontend:
    backend:
