version: "3.8"
services:
    db:
        image: postgres:12.6
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=test_sit_user
            - POSTGRES_DB=test_sit_db
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend
networks:
    backend:
volumes:
    pg_data:
