version: "3.9"
services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend
    webapp:
        ports:
            - "8000:80"
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=${POSTGRES_USER}
            - DB_NAME=${POSTGRES_DB}
            - DB_PASSWD=${POSTGRES_PASSWORD}
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    proxy:
        ports:
            - "8080:80"
        volumes:
            - .nginx/default.template.conf:/etc/nginx/templates/default.conf.template
volumes:
    pg_data:
networks:
    backend:
    frontend:
